name: riverpod_dependency
description:

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  flutter_riverpod: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_lint: ^2.3.0
#  riverpod_lint: ^2.1.1

  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
